### ISSUE TITLE
COVID-19 Statistics: Add tooltip on hover

### ISSUE THREAD

**Issue by paulmasson** [ladybug-tools/spider-2020#1]
@theo-armour  how about adding a tooltip displaying underlying data when hovering over a box? That would allow one to distinguish the test box off Africa from the real data. 

P.S. never thought of using `lookAt` to rotate objects. Nifty trick!

**Comment by theo-armour** [comment]
@paulmasson 

See https://www.ladybug.tools/spider-2020/cookbook/covid-19-statistics-on-globe/dev/

> P.S. never thought of using lookAt to rotate objects. Nifty trick!

it's one of the oldest Three.js examples. and it's one I asked Ricardo to do.

and, like me, it's cheap and cheerful

**Comment by paulmasson** [comment]
@theo-armour the two test boxes display mouse-over data for Hubei. Is that intended?

**Comment by theo-armour** [comment]
@paulmasson 
test box fix is cooking

**Comment by paulmasson** [comment]
@theo-armour consider using tooltips rather that info in the sideboard. A bit more immediate.

**Comment by theo-armour** [comment]
@paulmasson 

See latest

https://www.ladybug.tools/spider-2020/cookbook/covid-19-statistics-on-globe/covid-19-statistics-on-globe-2020-03-15-17.html

Which type of pop-u p do you prefer:

![image](https://user-images.githubusercontent.com/547626/76719276-822a0000-66f6-11ea-9481-1a4212912469.png)

or

![image](https://user-images.githubusercontent.com/547626/76719309-a38aec00-66f6-11ea-9810-88b653f47cea.png)

**Comment by paulmasson** [comment]
Rounded better

**Comment by theo-armour** [comment]
@paulmasson 

Done. Cynthia agrees
