### ISSUE TITLE
COVID-19 Statistics: Scaling of data

### ISSUE THREAD

**Issue by paulmasson** [ladybug-tools/spider-2020#2]
@theo-armour the current log scaling doesn't distinguish enough between China and Europe, since the latter looks far worse and that's not the reality. How about a square root or some other power? Also, Iran doesn't appear to show up at all in the current iteration.

**Comment by theo-armour** [comment]
@paulmasson 

See https://www.ladybug.tools/spider-2020/cookbook/covid-19-statistics-on-globe/dev/

Has  mouseover actions

**Comment by paulmasson** [comment]
@theo-armour Iran is there indeed. Didn't realize Italy had gotten so much worse so quickly!

**Comment by theo-armour** [comment]
@paulmasson 

Great suggestion! It's in:

https://www.ladybug.tools/spider-2020/cookbook/covid-19-statistics-on-globe/covid-19-statistics-on-globe-2020-03-15-17.html

**Comment by paulmasson** [comment]
@theo-armour much more dramatic. Although may need to scale all numbers down by a large amount if things get too bad (hope not!).
