### ISSUE TITLE
COVID-19 Statistic: Problem with South Korea

### ISSUE THREAD

**Issue by paulmasson** [ladybug-tools/spider-2020#3]
@theo-armour the country name is given as `"Korea, South"` in double quotes with a comma included. You can't just split on commas without massaging the data first.

**Comment by theo-armour** [comment]
@paulmasson 

Good catch! I had seen the faulty output and wondered why

**Comment by theo-armour** [comment]
@paulmasson 

not very scientific, but seems to work:

`response = response.replace( /Korea,/, "Korea" ).replace( /Virgin Islands,/, "Virgin Islands");`

**Comment by paulmasson** [comment]
@theo-armour please replace `Korea, South` with `South Korea` for legibility. I'd do a PR for this but I know from past collaboration that you'll likely overwrite my changes.
