### ISSUE TITLE
COVID-19 Statistics: Automatic parsing of /csse_covid_19_daily_reports/

### ISSUE THREAD

**Issue by paulmasson** [ladybug-tools/spider-2020#4]
@theo-armour since there's already a new file for 03-15-2020, how about automatic parsing of the data directory on load to find the latest?

Curious that they put the month first rather than the year. Then again, hopefully this won't be going on next year...

Also, you're declaring `url` twice, and without `let`. Shocking!

**Comment by theo-armour** [comment]
@paulmasson 
Just the lines I am looking at

**Comment by theo-armour** [comment]
@paulmasson 

Date is now set by checking against UTC. But I think JHU creates a new file at some arbitrary time during the day. if so, wil have to add some error trapping fall back thing.

**Comment by paulmasson** [comment]
Just use GitHub API, sort results and use latest.

**Comment by theo-armour** [comment]
@paulmasson 

yep - a better idea

**Comment by theo-armour** [comment]
@paulmasson 

Done
